### ISSUE TITLE
--show desugared-egglog --> --desugar

### ISSUE THREAD

**Issue by sergei-romanenko** [hatoo/egglog-language-server#11]
Pressing F8 results in an error:

```
Executing task: egglog --show desugared-egglog ~/egglog-playground/tests/herbie-tutorial.egg

error: unexpected argument '--show' found
```

It seems that in the fresh egglog version the option `--show desugared-egglog` has been replaced with `--desugar`.

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Changed the '--show desugared-egglog' option to '--desugar' in the egglog_desugar command to fix the error when pressing F8.

You can review changes in this commit: https://github.com/lattaai12/hatoo-egglog-language-server-11/commit/47bb06e40baed2d7b9af46011e6b09d6a6340c4c.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by hatoo** [comment]
Hmm, it's odd, `cargo run -- --show desugared-egglog /home/hatoo/egglog/tests/array.egg` works fine on the latest commit ca52ac13cb3c0bbacc8e7cc540789521d1019bd2

**Comment by sergei-romanenko** [comment]
Oh! I apologize! The problem is with egglog's installation instruction. It says:

```
make all
```

But, actually, it should say

```
make all
cargo install --path=.
```
Thus, I was trying to run an old version of egglog. With the fresh version, F8 produces the expected result.
